__title__ = 'codecov'
__description__ = 'Hosted coverage reports for GitHub, Bitbucket and Gitlab'
__url__ = 'https://github.com/codecov/codecov-python'
__version__ = '2.1.3'
__author__ = 'Codecov'
__author_email__ = 'support@codecov.io'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2020 Codecov'
